# Generated by Django 5.1.4 on 2025-01-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=11)),
                ('source', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('token', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='sso.sms', verbose_name='موبایل')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sso.sms')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tokens', to='sso.sms', verbose_name='پیام')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='sso.sms', verbose_name='مبدا')),
            ],
        ),
    ]
