# Generated by Django 5.1.4 on 2025-01-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
